// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: config.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct StockTesting_MarketPermission {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var level: String = String()

  var sseLevel: String = String()

  var cffLevel: String = String()

  var dceLevel: String = String()

  var czceLevel: String = String()

  var feLevel: String = String()

  var gilevel: String = String()

  var shfeLevel: String = String()

  var ineLevel: String = String()

  var hkperms: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct StockTesting_SDKConfig {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var appKey: String {
    get {return _storage._appKey}
    set {_uniqueStorage()._appKey = newValue}
  }

  var serverSites: Dictionary<String,String> {
    get {return _storage._serverSites}
    set {_uniqueStorage()._serverSites = newValue}
  }

  var marketPerm: StockTesting_MarketPermission {
    get {return _storage._marketPerm ?? StockTesting_MarketPermission()}
    set {_uniqueStorage()._marketPerm = newValue}
  }
  /// Returns true if `marketPerm` has been explicitly set.
  var hasMarketPerm: Bool {return _storage._marketPerm != nil}
  /// Clears the value of `marketPerm`. Subsequent reads from it will return its default value.
  mutating func clearMarketPerm() {_uniqueStorage()._marketPerm = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct StockTesting_TestcaseConfig {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var testcaseID: String = String()

  var continueWhenFailed: Bool = false

  var roundIntervalSec: Int64 = 0

  var paramStrs: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct StockTesting_RunnerConfig {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var jobID: String {
    get {return _storage._jobID}
    set {_uniqueStorage()._jobID = newValue}
  }

  var runnerID: String {
    get {return _storage._runnerID}
    set {_uniqueStorage()._runnerID = newValue}
  }

  var sdkConfig: StockTesting_SDKConfig {
    get {return _storage._sdkConfig ?? StockTesting_SDKConfig()}
    set {_uniqueStorage()._sdkConfig = newValue}
  }
  /// Returns true if `sdkConfig` has been explicitly set.
  var hasSdkConfig: Bool {return _storage._sdkConfig != nil}
  /// Clears the value of `sdkConfig`. Subsequent reads from it will return its default value.
  mutating func clearSdkConfig() {_uniqueStorage()._sdkConfig = nil}

  var casesConfig: [StockTesting_TestcaseConfig] {
    get {return _storage._casesConfig}
    set {_uniqueStorage()._casesConfig = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "stock_testing"

extension StockTesting_MarketPermission: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MarketPermission"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "Level"),
    2: .same(proto: "SseLevel"),
    3: .same(proto: "CffLevel"),
    4: .same(proto: "DceLevel"),
    5: .same(proto: "CzceLevel"),
    6: .same(proto: "FeLevel"),
    7: .same(proto: "GILevel"),
    8: .same(proto: "ShfeLevel"),
    9: .same(proto: "IneLevel"),
    10: .same(proto: "HKPerms"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.level)
      case 2: try decoder.decodeSingularStringField(value: &self.sseLevel)
      case 3: try decoder.decodeSingularStringField(value: &self.cffLevel)
      case 4: try decoder.decodeSingularStringField(value: &self.dceLevel)
      case 5: try decoder.decodeSingularStringField(value: &self.czceLevel)
      case 6: try decoder.decodeSingularStringField(value: &self.feLevel)
      case 7: try decoder.decodeSingularStringField(value: &self.gilevel)
      case 8: try decoder.decodeSingularStringField(value: &self.shfeLevel)
      case 9: try decoder.decodeSingularStringField(value: &self.ineLevel)
      case 10: try decoder.decodeRepeatedStringField(value: &self.hkperms)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.level.isEmpty {
      try visitor.visitSingularStringField(value: self.level, fieldNumber: 1)
    }
    if !self.sseLevel.isEmpty {
      try visitor.visitSingularStringField(value: self.sseLevel, fieldNumber: 2)
    }
    if !self.cffLevel.isEmpty {
      try visitor.visitSingularStringField(value: self.cffLevel, fieldNumber: 3)
    }
    if !self.dceLevel.isEmpty {
      try visitor.visitSingularStringField(value: self.dceLevel, fieldNumber: 4)
    }
    if !self.czceLevel.isEmpty {
      try visitor.visitSingularStringField(value: self.czceLevel, fieldNumber: 5)
    }
    if !self.feLevel.isEmpty {
      try visitor.visitSingularStringField(value: self.feLevel, fieldNumber: 6)
    }
    if !self.gilevel.isEmpty {
      try visitor.visitSingularStringField(value: self.gilevel, fieldNumber: 7)
    }
    if !self.shfeLevel.isEmpty {
      try visitor.visitSingularStringField(value: self.shfeLevel, fieldNumber: 8)
    }
    if !self.ineLevel.isEmpty {
      try visitor.visitSingularStringField(value: self.ineLevel, fieldNumber: 9)
    }
    if !self.hkperms.isEmpty {
      try visitor.visitRepeatedStringField(value: self.hkperms, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: StockTesting_MarketPermission, rhs: StockTesting_MarketPermission) -> Bool {
    if lhs.level != rhs.level {return false}
    if lhs.sseLevel != rhs.sseLevel {return false}
    if lhs.cffLevel != rhs.cffLevel {return false}
    if lhs.dceLevel != rhs.dceLevel {return false}
    if lhs.czceLevel != rhs.czceLevel {return false}
    if lhs.feLevel != rhs.feLevel {return false}
    if lhs.gilevel != rhs.gilevel {return false}
    if lhs.shfeLevel != rhs.shfeLevel {return false}
    if lhs.ineLevel != rhs.ineLevel {return false}
    if lhs.hkperms != rhs.hkperms {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension StockTesting_SDKConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SDKConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "appKey"),
    2: .same(proto: "serverSites"),
    3: .same(proto: "marketPerm"),
  ]

  fileprivate class _StorageClass {
    var _appKey: String = String()
    var _serverSites: Dictionary<String,String> = [:]
    var _marketPerm: StockTesting_MarketPermission? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _appKey = source._appKey
      _serverSites = source._serverSites
      _marketPerm = source._marketPerm
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._appKey)
        case 2: try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._serverSites)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._marketPerm)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._appKey.isEmpty {
        try visitor.visitSingularStringField(value: _storage._appKey, fieldNumber: 1)
      }
      if !_storage._serverSites.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._serverSites, fieldNumber: 2)
      }
      if let v = _storage._marketPerm {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: StockTesting_SDKConfig, rhs: StockTesting_SDKConfig) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._appKey != rhs_storage._appKey {return false}
        if _storage._serverSites != rhs_storage._serverSites {return false}
        if _storage._marketPerm != rhs_storage._marketPerm {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension StockTesting_TestcaseConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TestcaseConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "testcaseID"),
    2: .same(proto: "continueWhenFailed"),
    3: .same(proto: "roundIntervalSec"),
    4: .same(proto: "paramStrs"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.testcaseID)
      case 2: try decoder.decodeSingularBoolField(value: &self.continueWhenFailed)
      case 3: try decoder.decodeSingularInt64Field(value: &self.roundIntervalSec)
      case 4: try decoder.decodeRepeatedStringField(value: &self.paramStrs)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.testcaseID.isEmpty {
      try visitor.visitSingularStringField(value: self.testcaseID, fieldNumber: 1)
    }
    if self.continueWhenFailed != false {
      try visitor.visitSingularBoolField(value: self.continueWhenFailed, fieldNumber: 2)
    }
    if self.roundIntervalSec != 0 {
      try visitor.visitSingularInt64Field(value: self.roundIntervalSec, fieldNumber: 3)
    }
    if !self.paramStrs.isEmpty {
      try visitor.visitRepeatedStringField(value: self.paramStrs, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: StockTesting_TestcaseConfig, rhs: StockTesting_TestcaseConfig) -> Bool {
    if lhs.testcaseID != rhs.testcaseID {return false}
    if lhs.continueWhenFailed != rhs.continueWhenFailed {return false}
    if lhs.roundIntervalSec != rhs.roundIntervalSec {return false}
    if lhs.paramStrs != rhs.paramStrs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension StockTesting_RunnerConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RunnerConfig"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "jobID"),
    2: .same(proto: "runnerID"),
    3: .same(proto: "sdkConfig"),
    4: .same(proto: "casesConfig"),
  ]

  fileprivate class _StorageClass {
    var _jobID: String = String()
    var _runnerID: String = String()
    var _sdkConfig: StockTesting_SDKConfig? = nil
    var _casesConfig: [StockTesting_TestcaseConfig] = []

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _jobID = source._jobID
      _runnerID = source._runnerID
      _sdkConfig = source._sdkConfig
      _casesConfig = source._casesConfig
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularStringField(value: &_storage._jobID)
        case 2: try decoder.decodeSingularStringField(value: &_storage._runnerID)
        case 3: try decoder.decodeSingularMessageField(value: &_storage._sdkConfig)
        case 4: try decoder.decodeRepeatedMessageField(value: &_storage._casesConfig)
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._jobID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._jobID, fieldNumber: 1)
      }
      if !_storage._runnerID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._runnerID, fieldNumber: 2)
      }
      if let v = _storage._sdkConfig {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      }
      if !_storage._casesConfig.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._casesConfig, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: StockTesting_RunnerConfig, rhs: StockTesting_RunnerConfig) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._jobID != rhs_storage._jobID {return false}
        if _storage._runnerID != rhs_storage._runnerID {return false}
        if _storage._sdkConfig != rhs_storage._sdkConfig {return false}
        if _storage._casesConfig != rhs_storage._casesConfig {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
